---
  - name: Update apt cache and repo
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Upgrade packages
    apt:
      upgrade: dist
      force_apt_get: yes

  - name: Check if a reboot is needed
    register: reboot_needed
    stat:
      path: /var/run/reboot-required
      get_md5: no

  - name: Reboot the server if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for OS updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_needed.stat.exists