version: "3.8"

volumes:
#### ADGUARD
  adguard-work:
  adguard-conf:

services:
## VPN
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=home.marioverde.com.br
      # ⚠️ Change the Web UI Password:
      - PASSWORD
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

## ADGUARD
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    network_mode: 'host'
    ports:
      - 53:53/udp
      - 8080:80/tcp 
      - 3000:3000/tcp 
    volumes:
      - adguard-work:/opt/adguardhome/conf
      - adguard-conf:/opt/adguardhome/work