version: "3.8"
services:
  csgoretake:
    image: timche/csgo:sourcemod
    #mem_limit: 2048m
    #cpus: 2
    environment:
      - CSGO_WS_API_KEY #Portainer
      - CSGO_MAP="de_mirage"
      - CSGO_MAX_PLAYERS=12
      - CSGO_HOSTNAME="16:9"
      - CSGO_RCON_PW
      - CSGO_FORCE_NETSETTINGS=true
      - CSGO_GSLT
    volumes:
      - csgoretake:/home/csgo/server
    network_mode: host

  blackmesa:
    image: lacledeslan/gamesvr-blackmesa
    command: ./srcds_run -game bms +map gasworks +maxplayers 4
    volumes:
      - blackmesa:/app
    network_mode: host

volumes:
  csgoretake:
  blackmesa: