proxmox:
  hosts:
    csgo.home:
    containers.home:
    vpn.home:
  vars:
    ansible_user: luigi
    ansible_become: true

dockerhost:
  hosts:
    containers.home:
  vars:
    ansible_user: luigi
    ansible_become: true

dockeragent:
  hosts:
    csgo.home:
  vars:
    ansible_user: luigi
    ansible_become: true

nomad:
  hosts:
    nomad.home:
  vars:
    ansible_user: root
    docker_users:
      - nomad

zomboid:
  hosts:
    zomboid.home:
  vars:
    ansible_user: root

ftp:
  hosts:
    ac.home:
  vars:
    ansible_user: root