services:
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=https://grafana.intranet.marioverde.com.br
    ports:
     - '3000:3000'
  volumes:
      - grafana-storage:/var/lib/grafana
