- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters

        - type: videos
          channels:
            - UCferfyAeOJAjS9GoI4td6gg # Canal peewee
            - UCXdXbm5P-8UIQRNjF94uHTA # Derrotando filmes
            - UC42ZBFGMKZkg4YaQ_T6pNEw # Cortes do Cescon
            - UC2Gu2D6VkeVYwXA8wnLvSwg # Aryun
            - UCDO__Z-tZD4bfG9m4AkK_uA # NotOtzarva
            - UCI4aITQ3nx1QR_8RxFlPjRQ # Hens333
            - UCwhYSrP7BT480a75aFAvIeg # NotHens333
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
        - type: custom-api
          title: Steam Specials
          cache: 12h
          url: https://store.steampowered.com/api/featuredcategories?cc=br
          template: |
            <ul class="list list-gap-10 collapsible-container" data-collapse-after="5">
            {{ range .JSON.Array "specials.items" }}
            <li>
              <a class="size-h4 color-highlight block text-truncate" href="https://store.steampowered.com/app/{{ .Int "id" }}/">{{ .String "name" }}</a>
              <ul class="list-horizontal-text">
                <li>{{ .Int "final_price" | toFloat | mul 0.01 | printf "R$%.2f" }}</li>
                {{ $discount := .Int "discount_percent" }}
                <li{{ if ge $discount 40 }} class="color-positive"{{ end }}>{{ $discount }}% off</li>
                </ul>
              </li>
            {{ end }}
            </ul>
    - size: small
      widgets:
        - type: weather
          location: São Paulo, Brazil
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true

        - type: twitch-channels
          channels:
            - luigimarqs
            - luigimarqs_dj
            - djmozao_
            - devMozao
            - otzdarva
            - mynameispit
            - gamesdonequick
            - DanielGray10
            - Hens333