services:
  app:
    image: ghcr.io/p-adamiec/free-games-claimer-remaster:${FGC_TAG:-latest}
    container_name: fgc-remaster
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - fgc_data:/fgc/data
    env_file:
      - .env
    networks:
      - free_games_claimer_network
    healthcheck:
      test: pgrep python3 && curl --fail http://localhost:7080 || exit 1
      interval: 10s
      timeout: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fgc-remaster.rule=Host(`freegames.lab.marioverde.com.br`)"
      - "traefik.http.routers.fgc-remaster.entrypoints=websecure"
      - "traefik.http.routers.fgc-remaster.tls.certresolver=cloudflare"
      - "traefik.http.services.fgc-remaster.loadbalancer.server.port=7080"

networks:
  free_games_claimer_network:
    driver: bridge

volumes:
  fgc_data:
