- name: Create volume for portainer
  community.docker.docker_volume:
    name: portainer_data
  tags: host

- name: Create a host portainer container
  community.docker.docker_container:
      name: portainer
      image: portainer/portainer-ce:2.18.3
      state: started
      volumes:
        - portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports: 
        - "8000:8000"
        - "9443:9443"
      restart_policy: "always"
  tags: host

- name: Create agent portainer container
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:2.18.3
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
  tags: agent
