---
- name: Install Docker & PIP (For managing container wirh ansible)
  include_role:
    name: "{{ item }}"
  with_items:
    - geerlingguy.pip
    - geerlingguy.docker
  vars:
    become: true
    pip_install_packages:
      - name: docker
  tags: installdocker
