- hosts: nomad
  become: yes
  tasks:
    #NOMAD USER ADDED IN DOCKER GROUP BECAUSE OF VARIABLE AT INVENTORY!!!!!
    - name: install docker
      ansible.builtin.import_role:
        name: docker
    - name: install nomad
      ansible.builtin.import_role:
        name: nomad
    - name: install vault
      ansible.builtin.import_role:
        name: vault # I NEED TO MANUALLY CREATE THIS ROLE BTW